schema_version: 2

experiment:
  name: ppo_plane_kl_finetune
  seed: 42
  output_dir: runs/ppo_plane_finetune

environment:
  id: horcrux_env/plane-v0
  kwargs:
    joy_input_random: false
    joy_input: [1.0, 0.0, 0.0]
    use_friction_chg: false
    terminate_when_unhealthy: true
    unhealthy_max_steps: 30
    use_imu_window: false
    use_vels_window: false

sampling:
  num_envs: 8
  vec_env: subproc
  start_method: spawn

normalization:
  enabled: true
  clip_obs: 10.0
  epsilon: 1.0e-8

action_normalization:
  enabled: true

resume:
  model_path: policies/path_tracking/forward/01_initial_sb3_baseline/evaluation/best_model.zip
  vecnormalize_path: policies/path_tracking/forward/01_initial_sb3_baseline/evaluation/best_model_vecnormalize.pkl

algorithm:
  name: PPO
  policy: MlpPolicy
  device: auto
  kwargs:
    learning_rate: 0.0001
    gamma: 0.95
    n_steps: 512
    batch_size: 512
    n_epochs: 3
  policy_kwargs:
    net_arch: [512, 512, 512, 512, 512]
    activation_fn: tanh

training:
  total_timesteps: 100000

evaluation:
  enabled: true
  eval_freq: 100000
  n_eval_episodes: 3
  deterministic: true

checkpointing:
  enabled: true
  save_freq: 100000

video:
  enabled: true
  start_iteration: 10
  record_every_iterations: 100
  video_length: 300
  deterministic: true
