"""CoRL 2026 리부탈용 관절 수 스케일링(n-DOF) MJCF 생성기.

원본 14-DOF 모델(../resources/horcrux_p.xml)을 파싱해 head/h-link/v-link
바디를 템플릿으로 추출한 뒤, 관절 수 n짜리 체인으로 재조립한다.
원본 파일은 읽기만 하며 절대 수정하지 않는다.

생성 파일 (이 디렉토리):
    horcrux_n{N:02d}.xml        본체 모델 (n개 힌지 관절)
    horcrux_plane_n{N:02d}.xml  평지 월드 (본체 include + floor)

사용법:
    python generate_scalable_mjcf.py              # n=6,10,14,20 생성 + n=14 등가성 검증
    python generate_scalable_mjcf.py --n 8 16     # 임의 n 생성
    python generate_scalable_mjcf.py --no-validate
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
SRC_DIR = HERE.parent / "resources"
SRC_BODY = SRC_DIR / "horcrux_p.xml"

LINK_SPACING = "-0.0685 0 0"


def _rewrite_asset_paths(asset: ET.Element) -> None:
    """mesh 경로를 이 디렉토리 기준 상대경로로 바꾼다 (에셋은 원본 공유)."""
    for mesh in asset.iter("mesh"):
        f = mesh.get("file", "")
        if f.startswith("./assets/"):
            mesh.set("file", "../resources/assets/" + f[len("./assets/") :])


def _strip_child_bodies(body: ET.Element) -> int:
    """link* 자식 바디를 제거하고, 첫 제거 위치(원래 문서 순서상 인덱스)를 돌려준다."""
    idx = len(list(body))
    for child in list(body):
        if child.tag == "body" and child.get("name", "").startswith("link"):
            idx = min(idx, list(body).index(child))
            body.remove(child)
    return idx


def _rename_link(body: ET.Element, idx: int) -> None:
    """템플릿 바디의 이름 붙은 요소들을 link{idx} 규칙으로 갱신한다."""
    body.set("name", f"link{idx}")
    joint = body.find("joint")
    if joint is not None:
        joint.set("name", f"joint{idx - 1}")
    for site in body.findall("site"):
        name = site.get("name", "")
        if name.endswith("_top"):
            site.set("name", f"s_link{idx}_top")
        elif name.endswith("_bot"):
            site.set("name", f"s_link{idx}_bot")
    for geom in body.findall("geom"):
        if geom.get("name", "").startswith("collision-link"):
            geom.set("name", f"collision-link{idx}")


def _build_actuators(n: int) -> ET.Element:
    actuator = ET.Element("actuator")
    for i in range(1, n + 1):
        ET.SubElement(
            actuator,
            "motor",
            name=f"motor_{i}",
            ctrllimited="true",
            ctrlrange="-3.0 3.0",
            gear="1",
            joint=f"joint{i}",
        )
    return actuator


def _build_sensors(n: int) -> ET.Element:
    """원본과 동일한 순서: jpos, jvel, jtor, touch top, touch bot, head IMU.

    touch는 원본과 동일하게 마지막 링크(link{n+1})를 제외한 link1..link{n}.
    """
    sensor = ET.Element("sensor")
    for i in range(1, n + 1):
        ET.SubElement(sensor, "jointpos", name=f"pos_joint{i}", joint=f"joint{i}")
    for i in range(1, n + 1):
        ET.SubElement(sensor, "jointvel", name=f"vel_joint{i}", joint=f"joint{i}")
    for i in range(1, n + 1):
        ET.SubElement(sensor, "actuatorfrc", name=f"tor_joint{i}", actuator=f"motor_{i}")
    for i in range(1, n + 1):
        ET.SubElement(sensor, "touch", name=f"top_link{i}", site=f"s_link{i}_top")
    for i in range(1, n + 1):
        ET.SubElement(sensor, "touch", name=f"bot_link{i}", site=f"s_link{i}_bot")
    ET.SubElement(sensor, "framequat", name="head_quat", objtype="site", objname="s_tool")
    ET.SubElement(sensor, "gyro", name="head_angvel", site="s_tool")
    ET.SubElement(sensor, "accelerometer", name="head_linacc", site="s_tool")
    return sensor


def generate_body_xml(n: int) -> Path:
    src = ET.parse(SRC_BODY)
    src_root = src.getroot()

    worldbody = src_root.find("worldbody")
    link1 = worldbody.find("./body[@name='link1']")
    h_tmpl = link1.find("./body[@name='link2']")
    v_tmpl = h_tmpl.find("./body[@name='link3']")

    # 템플릿 확보 (원본 트리에서 분리된 deep copy)
    h_tmpl = copy.deepcopy(h_tmpl)
    v_tmpl = copy.deepcopy(v_tmpl)
    _strip_child_bodies(h_tmpl)
    _strip_child_bodies(v_tmpl)

    # 새 루트 구성: 원본 구조를 그대로 가져와 체인만 교체
    root = copy.deepcopy(src_root)
    root.set("model", f"Horcrux v2 body n{n}")
    root.insert(
        0,
        ET.Comment(
            f" AUTO-GENERATED by generate_scalable_mjcf.py (n={n} joints). "
            f"DO NOT EDIT — regenerate instead. Source: resources/horcrux_p.xml "
        ),
    )
    _rewrite_asset_paths(root.find("asset"))

    new_link1 = root.find("worldbody").find("./body[@name='link1']")
    # link2 이하 제거 후, com 카메라 바디보다 앞인 원래 자리에 체인을 삽입해
    # body 문서 순서(= MuJoCo body id 순서)를 원본과 동일하게 유지한다.
    chain_pos = _strip_child_bodies(new_link1)

    # link2..link{n+1} 체인 조립: 짝수 링크=h-link(Y축 관절), 홀수 링크=v-link(Z축 관절)
    parent, insert_at = new_link1, chain_pos
    for idx in range(2, n + 2):
        tmpl = h_tmpl if idx % 2 == 0 else v_tmpl
        link = copy.deepcopy(tmpl)
        link.set("pos", LINK_SPACING)
        _rename_link(link, idx)
        parent.insert(insert_at, link)
        parent, insert_at = link, len(list(link))

    # 액추에이터/센서 교체
    for tag, builder in (("actuator", _build_actuators), ("sensor", _build_sensors)):
        old = root.find(tag)
        pos = list(root).index(old)
        root.remove(old)
        root.insert(pos, builder(n))

    ET.indent(root, space="    ")
    out = HERE / f"horcrux_n{n:02d}.xml"
    ET.ElementTree(root).write(out, encoding="unicode")
    out.write_text(out.read_text() + "\n")
    return out


WORLD_TEMPLATE = """<!-- AUTO-GENERATED by generate_scalable_mjcf.py (n={n} joints). DO NOT EDIT.
 CoRL 2026 rebuttal: joint-count scaling experiment. Same plane world as
 resources/horcrux_plane.xml (timestep/floor/friction identical). -->

<mujoco model="Horcrux v2 n{n} with flat plane">
    <include file="horcrux_n{n:02d}.xml"/>
    <option timestep="0.005"/>

    <asset>
        <texture type="skybox" builtin="gradient" width="512" height="512" rgb1=".4 .6 .8" rgb2="0 0 0"/>
        <texture name="texgeom" type="cube" builtin="flat" mark="cross" width="128" height="128"
                 rgb1="0.6 0.6 0.6" rgb2="0.6 0.6 0.6" markrgb="1 1 1"/>
        <texture name="texplane" type="2d" builtin="checker" rgb1=".55 .55 .55" rgb2=".75 .75 .75"
                 width="512" height="512"/>
        <material name="MatPlane" reflectance="0.0" texture="texplane" texrepeat="1 1" texuniform="true"
                  rgba="1 1 1 1"/>
        <material name="capsule" texture="texgeom" texuniform="true" rgba=".4 .9 .6 1" />
        <material name="ellipsoid" texture="texgeom" texuniform="true" rgba=".4 .6 .9 1" />
        <material name="box" texture="texgeom" texuniform="true" rgba=".4 .9 .9 1" />
        <material name="cylinder" texture="texgeom" texuniform="true" rgba=".8 .6 .8 1" />
        <material name="sphere" texture="texgeom" texuniform="true" rgba=".9 .1 .1 1" />
    </asset>

<worldbody>
    <geom name="floor" type="plane" size="30 30 .5" priority="2" friction="0.65 0.015 0.01" material="MatPlane"/>
</worldbody>

</mujoco>
"""


def generate_world_xml(n: int) -> Path:
    out = HERE / f"horcrux_plane_n{n:02d}.xml"
    out.write_text(WORLD_TEMPLATE.format(n=n))
    return out


def sanity_check(n: int) -> None:
    import mujoco

    model = mujoco.MjModel.from_xml_path(str(HERE / f"horcrux_plane_n{n:02d}.xml"))
    expect_nq, expect_nu, expect_nsensor = 7 + n, n, 5 * n + 10
    assert model.nq == expect_nq, f"n={n}: nq {model.nq} != {expect_nq}"
    assert model.nu == expect_nu, f"n={n}: nu {model.nu} != {expect_nu}"
    assert model.nsensordata == expect_nsensor, (
        f"n={n}: nsensordata {model.nsensordata} != {expect_nsensor}"
    )
    total_mass = sum(model.body_mass)
    print(
        f"  n={n:2d}: nq={model.nq} nu={model.nu} nsensordata={model.nsensordata} "
        f"nbody={model.nbody} total_mass={total_mass:.3f} kg — OK"
    )


def validate_n14_equivalence(steps: int = 2000) -> None:
    """생성된 n=14 모델이 원본과 물리적으로 등가인지 검증한다.

    파라미터 비교 + 동일 토크 시퀀스 롤아웃의 qpos 궤적 비교.
    """
    import mujoco
    import numpy as np

    ref = mujoco.MjModel.from_xml_path(str(SRC_DIR / "horcrux_plane.xml"))
    gen = mujoco.MjModel.from_xml_path(str(HERE / "horcrux_plane_n14.xml"))

    for attr in ("nq", "nv", "nu", "nbody", "njnt", "nsensordata"):
        r, g = getattr(ref, attr), getattr(gen, attr)
        assert r == g, f"{attr}: ref {r} != gen {g}"
    for attr in ("body_mass", "jnt_range", "dof_damping", "dof_armature",
                 "actuator_ctrlrange", "geom_friction", "opt.timestep"):
        obj_r, obj_g = ref, gen
        name = attr
        if attr.startswith("opt."):
            obj_r, obj_g, name = ref.opt, gen.opt, attr[4:]
        r, g = np.asarray(getattr(obj_r, name)), np.asarray(getattr(obj_g, name))
        assert r.shape == g.shape and np.allclose(r, g), f"{attr} mismatch"

    d_ref, d_gen = mujoco.MjData(ref), mujoco.MjData(gen)
    rng_phase = np.linspace(0.0, np.pi, 14)
    for k in range(steps):
        t = k * ref.opt.timestep
        ctrl = 1.5 * np.sin(2 * np.pi * 0.5 * t + rng_phase)
        d_ref.ctrl[:] = ctrl
        d_gen.ctrl[:] = ctrl
        mujoco.mj_step(ref, d_ref)
        mujoco.mj_step(gen, d_gen)
    diff = float(np.max(np.abs(d_ref.qpos - d_gen.qpos)))
    assert diff < 1e-9, f"qpos trajectory diverged: max|diff|={diff:.3e}"
    print(f"  n=14 equivalence: params identical, {steps}-step rollout "
          f"max|qpos diff|={diff:.3e} — OK")


def render_preview(n: int, width: int = 800, height: int = 500) -> Path:
    """모델 미리보기 PNG를 previews/에 저장한다 (headless: MUJOCO_GL=egl 필요)."""
    import mujoco
    import numpy as np
    from PIL import Image

    model = mujoco.MjModel.from_xml_path(str(HERE / f"horcrux_plane_n{n:02d}.xml"))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)

    renderer = mujoco.Renderer(model, height=height, width=width)
    cam = mujoco.MjvCamera()
    # 머리~꼬리 중앙을 바라보고, 몸길이에 비례해 거리를 잡는다
    cam.lookat[:] = [data.body("link1").xpos[0] - 0.0685 * (n / 2), 0, 0]
    cam.distance = 0.35 * n * 0.0685 + 1.2
    cam.azimuth, cam.elevation = 90, -35
    renderer.update_scene(data, camera=cam)
    pixels = renderer.render()
    renderer.close()

    out_dir = HERE / "previews"
    out_dir.mkdir(exist_ok=True)
    out = out_dir / f"horcrux_n{n:02d}.png"
    Image.fromarray(np.asarray(pixels)).save(out)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, nargs="+", default=[6, 10, 14, 20])
    parser.add_argument("--no-validate", action="store_true")
    parser.add_argument("--render-previews", action="store_true",
                        help="previews/에 모델 미리보기 PNG 저장 (MUJOCO_GL=egl 권장)")
    args = parser.parse_args()

    for n in args.n:
        body = generate_body_xml(n)
        world = generate_world_xml(n)
        print(f"generated: {body.name}, {world.name}")

    if not args.no_validate:
        print("validating:")
        for n in args.n:
            sanity_check(n)
        if 14 in args.n:
            validate_n14_equivalence()

    if args.render_previews:
        print("rendering previews:")
        for n in args.n:
            out = render_preview(n)
            print(f"  {out.relative_to(HERE)}")


if __name__ == "__main__":
    main()
